### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mengzhibin** [NVIDIA/cuda-samples#17] opened 2019-10-15 07:03 UTC
desktop of dell with 1070Ti
input make in cuda-sample dir. 
Error occurs as below:
`make[1]: Entering directory '/home/mengzhibin/CLionProjects/cuda-samples/Samples/p2pBandwidthLatencyTest'
/usr/local/cuda/bin/nvcc -ccbin g++ -I../../Common  -m64    -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75 -o p2pBandwidthLatencyTest.o -c p2pBandwidthLatencyTest.cu
Segmentation fault (core dumped)
Makefile:290: recipe for target 'p2pBandwidthLatencyTest.o' failed
make[1]: *** [p2pBandwidthLatencyTest.o] Error 139
make[1]: Leaving directory '/home/mengzhibin/CLionProjects/cuda-samples/Samples/p2pBandwidthLatencyTest'
Makefile:45: recipe for target 'Samples/p2pBandwidthLatencyTest/Makefile.ph_build' failed
make: *** [Samples/p2pBandwidthLatencyTest/Makefile.ph_build] Error 2
`

**Comment by mdoijade** [comment] 2019-10-15 09:14
@mengzhibin I cannot reproduce this issue at my end. can you share more details, as in which cuda toolkit version you are using? and which OS?

**Comment by mengzhibin** [comment] 2019-10-17 07:04
Cuda info:
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Mon_Mar_11_22:07:30_CDT_2019
Cuda compilation tools, release 10.0, V10.0.326
`
nvidia driver info:430.14
Os : ubuntu 18.04
Thanks very much

**Comment by mdoijade** [comment] 2019-10-23 13:29
@mengzhibin no the cuda samples in this repo only support Makefiles.
Are you facing the segfault with only p2pBandwidthLatencyTest sample? or other samples as well?
Can you run the Makefile with EXTRA_NVCCFLAGS="-v" and share the output result for p2pBandwidthLatencyTest ?

**Comment by mdoijade** [comment] 2019-11-12 11:31
based on response since 3 weeks closing this issue @mengzhibin

**Closed by mdoijade** 2019-11-12 11:31 UTC
