### ISSUE TITLE
cudamalloc error

### ISSUE THREAD

**Issue by sunbinbin1991** [NVIDIA/cuda-samples#19] opened 2019-11-13 13:49 UTC
Here is a problem confuse me a lot;
At first I use cudasetDevice set use device =1, then I don't know why, it change to gpu device=0 suddenly. Then i cudamalloc space to store gpu data, it has following error,cuda error code is **70**, anyone has  some idea ? 
Also, if I set device =0, cudamalloc is normal, no error occur, but i really want to know why this happen!
```
========= CUDA-MEMCHECK
========= Invalid __global__ read of size 4
=========     at 0x00000490 in void gemv2T_kernel_val<float, float, float, int=128, int=16, int=2, int=2, bool=0>(int, int, float, float const *, int, float const *, int, float, float*, int)
=========     by thread (95,0,0) in block (80,0,0)
=========     Address 0x7fe1d9f4283c is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuLaunchKernel + 0x2cd) [0x22b40d]```

**Comment by sunbinbin1991** [comment] 2019-11-16 15:13
Anyone help？

**Comment by mdoijade** [comment] 2019-11-26 11:33
@sunbinbin1991 it is not possible to root cause your issue based on the given details. also this is repo is for cuda samples hence only tracks the issues related to samples sources in this repo. Please file your issues with appropriate repro sources to relevant nvidia developer forums. Closing this issue.

**Closed by mdoijade** 2019-11-26 11:33 UTC
